# Generated by Django 3.1.5 on 2021-02-02 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Car-Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='WashType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of wash type')),
                ('percentage', models.IntegerField(default=100, verbose_name='Base price percentage')),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_owner',
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='car_wash.car'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='car_wash.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_end_date',
            field=models.DateTimeField(verbose_name='Schedule end time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_start_date',
            field=models.DateTimeField(verbose_name='Schedule start time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='washer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='car_wash.carwasher'),
        ),
        migrations.AddField(
            model_name='order',
            name='wash_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='car_wash.washtype'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_wash.cartype'),
        ),
    ]
