# Generated by Django 3.1.5 on 2021-02-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0002_auto_20210202_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_end_date',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_start_date',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
    ]
