# Generated by Django 3.1.6 on 2021-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0003_auto_20210207_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In Process', 'In Process'), ('Cancelled', 'Cancelled'), ('Finished', 'Finished')], max_length=200),
        ),
    ]
